/**
 * Where the Qaida section's letter audio comes from.
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │ SYNTHESISED AUDIO — TO BE REPLACED                                       │
 * │                                                                          │
 * │ The app currently plays speech generated by OpenAI's text-to-speech API  │
 * │ so the Qaida lesson is usable before a hafiz's recordings exist. It is │
 * │ a machine voice reading Arabic, not a reciter: good enough to learn the  │
 * │ shape of a letter from, not a model of tajwid.                           │
 * │                                                                          │
 * │ The clips are generated once by scripts/generate-letter-audio.mjs and    │
 * │ committed as static files. Nothing calls the API at playback time.       │
 * │                                                                          │
 * │ To swap to the hafiz set, change ONE line at the bottom of this file:    │
 * │                                                                          │
 * │     export const ACTIVE_LETTER_AUDIO_SOURCE = HAFIZ_RECORDINGS;          │
 * │                                                                          │
 * │ Both sources read the same directory under the same filenames, so the    │
 * │ recordings drop straight in over the generated ones. That single line    │
 * │ only changes how the audio is described to the learner.                  │
 * └──────────────────────────────────────────────────────────────────────────┘
 */
import type { Harakat } from "./arabicLetters";

export type LetterAudioSource = {
  /** Stable id, used in diagnostics and tests. */
  id: string;
  label: string;
  /** True while this is a stand-in rather than our own recordings. */
  isPlaceholder: boolean;
  /** Shown in the UI when the source is not ours. */
  attribution?: string;
  /**
   * URL for one recording, or null when this source has no file for it.
   *
   * Returning null matters: it is how a source says "I do not have this",
   * which the UI reports honestly instead of playing something else.
   */
  url(slug: string, harakat?: Harakat): string | null;
};

/** Public directory both local sources read. */
export const LETTER_AUDIO_DIR = "/audio/letters";

/**
 * The documented path for one recording:
 *
 *   letterAudioUrl("alif")          → /audio/letters/alif.mp3
 *   letterAudioUrl("alif", "fatha") → /audio/letters/alif-fatha.mp3
 *
 * Shared by both local sources on purpose. A hafiz recording named alif.mp3
 * replaces the generated alif.mp3 by sitting on top of it — that is what makes
 * the swap a drop-in rather than a migration.
 */
const letterAudioUrl = (slug: string, harakat?: Harakat) =>
  `${LETTER_AUDIO_DIR}/${harakat ? `${slug}-${harakat}` : slug}.mp3`;

/**
 * A qualified reciter's recordings. The target state, and what
 * docs/letter-recordings.md asks for: 28 letters × (alone + 3 harakat).
 */
export const HAFIZ_RECORDINGS: LetterAudioSource = {
  id: "hafiz",
  label: "Commissioned hafiz recordings",
  isPlaceholder: false,
  url: letterAudioUrl,
};

/**
 * The same files, while they are still machine-generated.
 *
 * Identical paths, different provenance — and provenance is all that differs:
 * `isPlaceholder` is what makes the UI say the voice is synthesised instead of
 * crediting a reciter for it.
 *
 * Generated by:
 *
 *   OPENAI_API_KEY=sk-... node scripts/generate-letter-audio.mjs
 *
 * which is a one-off — the 112 clips are committed, and no request is made at
 * playback time.
 */
export const OPENAI_TTS: LetterAudioSource = {
  id: "openai-tts",
  label: "OpenAI text-to-speech (synthesised)",
  isPlaceholder: true,
  attribution: "OpenAI text-to-speech",
  url: letterAudioUrl,
};

export const LETTER_AUDIO_SOURCES = [HAFIZ_RECORDINGS, OPENAI_TTS];

// ─── THE SWITCH ────────────────────────────────────────────────────────────
// Change this single line to HAFIZ_RECORDINGS once the recordings land.
export const ACTIVE_LETTER_AUDIO_SOURCE: LetterAudioSource = OPENAI_TTS;
